name: Update Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        space_name: [company-pet-policy, about-mls, shakespeare]  # List your Hugging Face space names here

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Install huggingface_hub
        run: pip install huggingface_hub

      - name: Login to Hugging Face (use secret token)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          huggingface-cli login --token $HF_TOKEN

      - name: Fetch changes from Hugging Face space
        run: git fetch space_${{ matrix.space_name }}

      - name: Diff changed files
        id: diff_files
        run: |
          git diff --name-only HEAD~1 HEAD || true

      - name: Push only changed files to Hugging Face space
        if: steps.diff_files.outputs.value != ''
        run: |
          changed_files=$(echo "${{ steps.diff_files.outputs.value }}")
          for file in $changed_files; do
            git checkout space_${{ matrix.space_name }}/main -- $file
            git add $file
            git commit -m "Update $file in ${{ matrix.space_name }}"
            git push space_${{ matrix.space_name }} HEAD:main
          done
