name: Sync and Push to Hugging Face

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  sync-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        space_name: [company-pet-policy, about-mls, shakespeare]  # List your Hugging Face space names here

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2
        with:
          repository: david-oplatka/chatbot-streamlit
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up SSH for Hugging Face
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure SSH known hosts for Hugging Face
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan hf.co >> ~/.ssh/known_hosts

      - name: Clone Target Hugging Face Repository
        run: |
          git clone git@hf.co:spaces/david-oplatka/${{ matrix.space_name }}.git tmp-folder-${{ matrix.space_name }}
          cd tmp-folder-${{ matrix.space_name }}
          git checkout main

      - name: Sync Source Repository with Temporary Folder
        run: |
          rsync -av --exclude '.git' . ./tmp-folder-${{ matrix.space_name }}/
          cd tmp-folder-${{ matrix.space_name }}
          git add .
          git commit -m "Sync updates from source repository"

      - name: Push changes to Hugging Face Space
        run: |
          git push git@hf.co:spaces/david-oplatka/${{ matrix.space_name }}.git main
